### ISSUE TITLE
TypeError: this.script.createCachedData is not a function

### ISSUE THREAD

**Issue by hulkish** [sokra/node-voo#2]
When using `NODE_VOO_LOGLEVEL=verbose NODE_VOO_YARN=true NODE_VOO_CACHE_DIRECTORY="$PWD/.cache/voo"`, [this code path](https://github.com/sokra/node-voo/blob/master/index.js#L238) seems to intermittently break:

```sh
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/html-webpack-plugin/lib/loader.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/tools/platform-config/webpack/babel-loader.js restored [unoptimized] 46 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/resolve/index.js restored [unoptimized] 7 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/babel-plugin-macros/dist/index.js restored [unoptimized] 1 modules
[node-voo] /Users/myuser/dev/repos/myrepo/tools/platform-config/babel/web.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/tools/platform-config/babel/web-vendor.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/mini-css-extract-plugin/dist/loader.js restored [unoptimized] 2 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/css-loader/dist/cjs.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/postcss-loader/src/index.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/sass-loader/lib/loader.js restored [unoptimized] 14 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/node-sass/lib/index.js restored [unoptimized] 7 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/postcss-preset-env/index.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/webpack/bin/webpack.js restructuring not worth it: 1 modules (9.7 kiB) could be removed
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/webpack/bin/webpack.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/webpack/bin/webpack.js|/Users/myuser/dev/repos/myrepo/services/storybook/webpack/web.config.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/tools/platform-config/webpack/babel-loader.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/resolve/index.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/babel-plugin-macros/dist/index.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/mini-css-extract-plugin/dist/loader.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/sass-loader/lib/loader.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/node-sass/lib/index.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/loader.js restored [unoptimized] 10 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/dist/loader/parsers/parser-js.js restored [unoptimized] 2 modules
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/loader.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/dist/loader/parsers/parser-js.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/html-loader/index.js restored [unoptimized] 167 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/markdown-loader/index.js restored [unoptimized] 2 modules
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/loader.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/@storybook/addon-storysource/dist/loader/parsers/parser-js.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/html-loader/index.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
ContextifyScript {}
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/markdown-loader/index.js failed to persist: TypeError: this.script.createCachedData is not a function
    at Voo.persist (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:239:31)
    at Timeout.timeout.setTimeout [as _onTimeout] (/Users/myuser/dev/repos/myrepo/node_modules/node-voo/index.js:478:9)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/svg-react-loader/lib/loader.js no cache file
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/file-loader/dist/cjs.js restored [unoptimized] 2 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/svg-react-loader/lib/options.js restored [unoptimized] 1 modules
[node-voo] /Users/myuser/dev/repos/myrepo/node_modules/svg-react-loader/lib/sanitize/filters/text-content.js restored [unoptimized] 1 modules
```

**Comment by sokra** [comment]
Which node version?

**Comment by hulkish** [comment]
`node@8.15.0`

**Comment by sokra** [comment]
createCachedData was added in: v10.6.0

So this is the minimal required node.js version.
